### ISSUE TITLE
run-local.bash was not found 

### ISSUE THREAD

**Issue by biocheming** [GHeinzelmann/GHOAT.py#2]
`$AMBERHOME/miniconda/bin/python GHOAT.py -i input.in -s equil`

This command will create an `./equil` folder, with one folder inside for each of the guests. In order to run the simulations for each guest, you can use the `run-local.bash` script (to run them locally), or the PBS-run script...
----------------
in the ./equil/run_files folder, there are 
`local-equil.bash  
local-lig.bash  
PBS-create  
PBS-fe   
PBS-sdr       
run-rest.bash          
run-sdr-missing.bash
local-fe.bash     
local-sdr.bash  
PBS-equil   
PBS-lig  
run-all.bash  
run-rest-missing.bash  
run-sdr-site.bash`
files, and `run-local.bash` was not found

**Comment by GHeinzelmann** [comment]
The run-local.bash file is already in the simulation folders, the ones you listed are the different templates to build it.

**Comment by biocheming** [comment]
> The run-local.bash file is already in the simulation folders, the ones you listed are the different templates to build it.

Thanks a lot. I found it in the guest-1 or guest-3 folder.
