### ISSUE TITLE
Question: How are translational contraints of the guest relative to the host provided to AMBER? 

### ISSUE THREAD

**Issue by GregorySchwing** [GHeinzelmann/GHOAT.py#3]
Dear Dr. Heinzelmann:

I am looking for where the restraints.in file is used to bias the translational degrees of freedom of the host.  I performed an 
$ egrep -R "restraints.in" * 

in the root directory , and the only results are in the analysis phase.  Am I correct to assume that the translational constraints of the guest relative to the host aren't enforced during the SDR simulations? Or are these restraints enforced by the disang.rest file?

**Comment by GHeinzelmann** [comment]
Hi Gregory. All restraints are enforced during the SDR calculations, and they are always defined in the disang.rest file. The restraints.in file will only be used in the analysis stage of the restraint folders, in order to read the time evolution of a given coordinate (distance, angle, etc.) from the trajectory.

**Comment by GregorySchwing** [comment]
Thank you for clarifying.  An additional question I have is the fe/guest-1/sdr/*/full.pdb/inpcrd file has two copies of the bulk and bound guests.  Perhaps this is an amber specific requirement, for I am used to namd where one would only need one copy.  Are the duplicates removed before running the simulation?

Thank you for your time.

**Comment by GHeinzelmann** [comment]
Hi. The two copies of the ligand are used in the electrostatic windows only (e), and are an amber requirement because you need one charged copy and another neutral one. One will be transformed to the other in bulk and in the protein.
